# Generated by Django 4.1.2 on 2022-10-26 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idade", models.IntegerField(null=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("nao_declarado", "Não declarado"),
                            ("outro", "Outro"),
                            ("masculino", "Masculino"),
                            ("feminino", "Feminino"),
                        ],
                        default="nao_declarado",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("bio", models.CharField(max_length=500)),
                ("profissao", models.CharField(max_length=255, null=True)),
                ("endereco", models.CharField(max_length=255, null=True)),
                ("numero", models.CharField(max_length=50, null=True)),
                ("cep", models.CharField(max_length=50, null=True)),
                ("cidade", models.CharField(max_length=100, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("PR", "PR"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
