# Generated by Django 4.1.2 on 2022-10-19 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquete",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("editado_em", models.DateTimeField(auto_now=True)),
                (
                    "texto",
                    models.CharField(max_length=255, verbose_name="Texto da enquete"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Escolha",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("editado_em", models.DateTimeField(auto_now=True)),
                ("texto", models.CharField(max_length=200, verbose_name="Escolha")),
                (
                    "num_votos",
                    models.IntegerField(default=0, verbose_name="Número de votos"),
                ),
                (
                    "enquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escolhas",
                        to="enquetes.enquete",
                        verbose_name="Enquete",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
