# Generated by Django 4.1.2 on 2022-10-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquetes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquete",
            name="data_pub",
            field=models.DateTimeField(null=True, verbose_name="Data de publicação"),
        ),
    ]
