# Generated by Django 4.1.2 on 2022-10-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquetes", "0002_enquete_data_pub"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquete",
            name="descricao",
            field=models.CharField(max_length=500, null=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="enquete",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagens_enquetes/"
            ),
        ),
    ]
